### ISSUE TITLE
Replace how the EVM receives the program to execute

### ISSUE THREAD

**Issue by JulianVentura** [lambdaclass/era_vm#116]
Currently, we are instantiating an evm using `EVM::new`, which receives a `Vec<U256>` as the program to execute. We may modify this logic so the program is received by the evm by other means.

**Comment by MarcosNicolau** [comment]
Are we sure this is actually an issue?

**Comment by juan518munoz** [comment]
Marking this issue as resolved as we are no longer instantiating with a `Vec<U256>`. Current function stands as:
`EVM::new(state: VMState, initial_storage: Rc<RefCell<dyn InitialStorage>>, contract_storage: Rc<RefCell<dyn ContractStorage>>)`
