### ISSUE TITLE
Modify error case on `run_program` function under `lib.rs` or delete it

### ISSUE THREAD

**Issue by JulianVentura** [lambdaclass/era_vm#117]
The function `run_program` from `lib.rs` executes the given program on the vm and returns the result on success, and returns a hardcoded `ExecutionOutput::Panic` on error. We may change this panic to an `Ok` or `Revert` with empty result data, or simply remove this function if its not being used.

**Comment by MarcosNicolau** [comment]
Solved in pr #134.
