### ISSUE TITLE
Implement `Memory` trait fully for `Heaps` or remove it

### ISSUE THREAD

**Issue by JulianVentura** [lambdaclass/era_vm#121]
Currently, we have a partial implementation of `trait Memory` for struct `Heaps`, panicking if `specialized_code_query` and `read_code_query` are called. We should implement those two methods or delete the trait implementation if it is not being used.

**Comment by gianbelinche** [comment]
This is done in order to use the precompiles implementation thats already done, the idea is to remove it completely and do it ourselves, here is the issue for that https://github.com/lambdaclass/era_vm/issues/94
