### ISSUE TITLE
Add RollBacks

### ISSUE THREAD

**Issue by gianbelinche** [lambdaclass/era_vm#47]
When doing a near call, the storage needs to be cloned, so that the state is the same, but the changes are not present on the previous callframe.
However, rocksdb cannot be cloned, so in order to implement this behaviour, a rollback mechanism needs to be implemented.
In this new format, the storage would be passed as is, and when the context is restored, the rollback should happend, restoring the previous state.

**Comment by juan518munoz** [comment]
Should we close this issue given that #108 is already in `main` and this [issue](https://github.com/lambdaclass/era_vm/issues/196) aims to get a complete implementation?

**Comment by gianbelinche** [comment]
> Should we close this issue given that #108 is already in `main` and this [issue](https://github.com/lambdaclass/era_vm/issues/196) aims to get a complete implementation?

That is fine, but lets remember that we need to optimize this later, it still going to be a rough implementation of rollbacks (we need to implement something like the rollbackable map the have on vm2)

**Comment by juan518munoz** [comment]
Agree, after the mentioned issue is resolved we should check if a full rollback is implemented, otherwise we should open a new issue.
